" Settings {{{

" Import some settings from external files
source ~/.vim/ext_settings/plugins/plugins.vim
source ~/.vim/ext_settings/plugins/plugins_settings.vim
source ~/.vim/ext_settings/plugins/tagbar_settings.vim
source ~/.vim/ext_settings/commands/commands.vim
source ~/.vim/ext_settings/commands/mappings.vim
source ~/.vim/ext_settings/commands/templates.vim
source ~/.vim/ext_settings/generic/functions.vim
source ~/.vim/ext_settings/generic/default_setting.vim

" }}}

