# This file was copied and edited from https://github.com/Integralist/ProVim/blob/master/.zshrc.
# If you need to view the original then go to the previousily mentioned URL.

# Exports {{{

## SET UP GIT
# Who git and github will see me as
export GITHUB_USER="randy1burrell"
# My git user
git config --global user.name "randy1burrell"
# My git email
git config --global user.email "randy1burrell@yahoo.com"

# Path to bin files
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin # Reorder PATH so local bin is first
export PATH={PATH}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:$HOME/vimpkg/bin:$HOME/.custom_scripts
# Add PATH for android sdk
export PATH=${PATH}:$HOME/Android/Sdk/tools
export PATH=${PATH}:$HOME/Android/Sdk/platform-tools
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH=$PATH:$HOME/.rvm/bin:/usr/local/jaxrs-ri/ext

# PATH to java home
export JAVA_HOME=/usr/lib/jvm/java-8-oracle/
export CATALINA_HOME=/usr/local/apache-tomcat-9.0.0.M22/

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

## SET UP COLOR
# Change grep color options
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'
# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"
# Set default editor to vim
export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
# Change terminal CLI colora
export TERM="xterm-256color"
export CLICOLOR=1
export LSCOLORS='di=1;35:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=0;35:*.rpm=90:*.tar=1;31'
export LS_COLORS='di=1;35:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=0;35:*.rpm=90:*.tar=1;31'


export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/.projects

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# }}}

# Theme, Plugins and Sourcing {{{
# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

ZSH_THEME="af-magic"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git django vim-interaction vi-mode virtualenv python pylint ubuntu git-remote-branch laravel grunt jsontools tmux pep8 branch jira postgres apache2-macports mysql-macports vundle frontend-search sudo bundler tmux-cssh github ruby)

# All sources for environment
source $ZSH/oh-my-zsh.sh
source /usr/local/bin/virtualenvwrapper.sh

if [ -f "${HOME}//.zsh//alias.zsh" ]
then
    source "${HOME}//.zsh//alias.zsh"
fi

# }}}


### Source {{{
if [ -f "${HOME}//.zsh_locals" ]
then
    source ${HOME}//.zsh_locals
fi

if [ -f "${HOME}//.zsh_prompt" ]
then
    source ${HOME}//.zsh_prompt
fi
# }}}

# Ruby {{{
function get_ruby_version() {
  ruby -v | awk '{print $1 " " $2}'
}
# }}}

# Tmux {{{
# Makes creating a new tmux session (with a specific name) easier
function tmuxopen() {
  tmux attach -t $1
}

# Makes creating a new tmux session (with a specific name) easier
function tmuxnew() {
  tmux new -s $1
}

# Makes deleting a tmux session easier
function tmuxkill() {
  tmux kill-session -t $1
}
# }}}

# Alias' {{{
alias vi="vim"
alias r="source ~/.zshrc"
alias tat='tmux new-session -As $(basename "$PWD" | tr . -)' # will attach if session exists, or create a new session
alias tmuxsrc="tmux source-file ~/.tmux.conf"
alias tmuxkillall="tmux ls | cut -d : -f 1 | xargs -I {} tmux kill-session -t {}" # tmux kill all sessions
alias ct="ctags -R --exclude=.git --exclude=node_modules"
alias dotfiles="ls -a | grep '^\.' | grep --invert-match '\.DS_Store\|\.$'"
# }}}

# History {{{
HISTSIZE=10000
SAVEHIST=9000
HISTFILE=~/.zsh_history
# }}}

# Zsh Hooks {{{
function precmd {
  # vcs_info
  # Put the string "hostname::/full/directory/path" in the title bar:
  echo -ne "\e]2;$PWD\a"

  # Put the parentdir/currentdir in the tab
  echo -ne "\e]1;$PWD:h:t/$PWD:t\a"
}
# }}}
